import { memo, useMemo } from "react";
import type { ReactElement } from "react";
import type { GeminiTravelPayload } from "@/lib/types";

/** Props for {@link DiscoveryPanel}. */
export interface DiscoveryPanelProps {
  /** The raw model-generated payload (hidden gems, events, and heritage story). */
  payload: GeminiTravelPayload;
}

/**
 * Splits a multi-paragraph narrative on blank lines so each paragraph
 * renders as its own `<p>` instead of one unbroken block of text.
 */
function paragraphsOf(narrative: string): string[] {
  return narrative
    .split(/\n{2,}/)
    .map((paragraph) => paragraph.trim())
    .filter((paragraph) => paragraph.length > 0);
}

/**
 * Cultural discovery content beyond the day-by-day plan: hidden gems, local
 * events, and an immersive heritage story, exactly as generated by the
 * model.
 */
function DiscoveryPanelComponent({ payload }: DiscoveryPanelProps): ReactElement {
  const storyParagraphs = useMemo(
    () => paragraphsOf(payload.story.narrative),
    [payload.story.narrative]
  );

  return (
    <div className="flex flex-col gap-6">
      {payload.hiddenGems.length > 0 && (
        <section
          aria-labelledby="gems-heading"
          className="flex flex-col gap-3 rounded-xl border border-stone-300 bg-white p-5 shadow-sm sm:p-6"
        >
          <h2 id="gems-heading" className="text-xl font-bold text-stone-900">
            Hidden gems
          </h2>
          {payload.hiddenGems.map((gem) => (
            <article key={gem.name} className="rounded-md border border-stone-300 p-3">
              <h3 className="font-semibold text-stone-900">{gem.name}</h3>
              <p className="mt-1 text-sm text-stone-700">{gem.description}</p>
              <p className="mt-2 text-sm text-stone-800">
                <strong>Local tip:</strong> {gem.localTip}
              </p>
            </article>
          ))}
        </section>
      )}

      {payload.events.length > 0 && (
        <section
          aria-labelledby="events-heading"
          className="flex flex-col gap-3 rounded-xl border border-stone-300 bg-white p-5 shadow-sm sm:p-6"
        >
          <h2 id="events-heading" className="text-xl font-bold text-stone-900">
            Cultural events
          </h2>
          {payload.events.map((event) => (
            <article key={event.name} className="rounded-md border border-stone-300 p-3">
              <h3 className="font-semibold text-stone-900">{event.name}</h3>
              <p className="mt-1 text-sm text-stone-700">{event.description}</p>
              <p className="mt-2 text-sm text-stone-800">
                <strong>Best time:</strong> {event.bestTime}
              </p>
            </article>
          ))}
        </section>
      )}

      <section
        aria-labelledby="story-heading"
        className="flex flex-col gap-3 rounded-xl border border-amber-300 bg-amber-50 p-5 shadow-sm sm:p-6"
      >
        <h2 id="story-heading" className="text-xl font-bold text-amber-950">
          {payload.story.title}
        </h2>
        <div className="flex flex-col gap-3 rounded-md border border-amber-200 bg-white p-4 font-serif text-base leading-relaxed text-stone-800">
          {storyParagraphs.map((paragraph, index) => (
            <p key={`${index}-${paragraph}`}>{paragraph}</p>
          ))}
        </div>
      </section>
    </div>
  );
}

/**
 * Memoized discovery panel. See {@link DiscoveryPanelComponent} for behavior.
 */
export const DiscoveryPanel = memo(DiscoveryPanelComponent);
